### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by Francisc**

### CODE REVIEW

**Comment by Francisc** [comment]
Also, on line 298 of the same file, shouldn't this:
```
const productReq = await product.url
```
have a `fetch()` call?

**Comment by bevacqua** [comment]
Looks like it yes

**Comment by Francisc** [comment]
Let me know if you want me to subit the fix for that bit of code.
Otherwise, thanks for the merge.

**Comment by bevacqua** [comment]
Please do :)

**Pull request merged**
